name: UI and Backend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ========== Install Dependencies ==========
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # ========== Build Frontend ==========
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # ========== Start Backend ==========
      - name: Start Backend
        run: |
          cd backend
          npm run dev &
        env:
          PORT: 4000

      # ========== Start Frontend Preview Server ==========
      - name: Start Frontend Preview Server
        run: |
          cd frontend
          npm run preview -- --port 5173 &
        env:
          PORT: 5173

      # ========== Wait for Servers ==========
      - name: Wait for Backend to be Ready
        run: npx wait-on http://localhost:4000/api/items

      - name: Wait for Frontend to be Ready
        run: npx wait-on http://localhost:5173

      # ========== Install Playwright ==========
      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      # ========== Run Tests ==========
      - name: Run API Tests
        run: |
          cd backend
          npm test

      - name: Run UI Tests (Playwright)
        run: |
          cd frontend
          npx playwright test

      # ========== Upload Playwright Report on Failure ==========
      - name: Upload Playwright Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report