name: UI and Backend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ========== Install Dependencies ==========
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # ========== Start Backend ==========
      - name: Start Backend
        run: |
          cd backend
          npm run dev &
        env:
          PORT: 4000
      # ========== Start Frontend ==========
      - name: Start Frontend
        run: |
          cd frontend
          npm run dev &
        env:
          PORT: 3000

      # ========== Wait for Servers ==========
      - name: Wait for Backend to be Ready
        run: |
          npx wait-on http://localhost:4000/api/items

      - name: Wait for Frontend to be Ready
        run: |
          npx wait-on http://localhost:3000

      # ========== Install Playwright Browsers ==========
      - name: Install Playwright
        run: |
          cd frontend
          npx playwright install --with-deps

      # ========== Run Tests ==========
      - name: Run API Tests
        run: |
          cd backend
          npm test

      - name: Run UI Tests (Playwright)
        run: |
          cd frontend
          npx playwright test

      # ========== Upload Test Artifacts if UI Fails ==========
      - name: Upload Playwright Report on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: frontend/playwright-report